firstdbtproject:
  target: ci

  outputs:
    ci:
      type: snowflake
      account: dummy_account
      user: dummy_user
      password: dummy_password
      role: dummy_role
      database: dummy_database
      warehouse: dummy_warehouse
      schema: dummy_schema
      threads: 1